export type Product = {
  id: string
  slug: string
  name: string
  nameAr: string
  category: "vertical" | "horizontal" | "galvanized" | "painted" | "custom"
  orientation: "vertical" | "horizontal" | "custom"
  finish: "galvanized" | "painted" | "custom"
  capacity: string
  capacityL: number
  workingPressure: string
  testPressure: string
  motorHP: string
  weight: string
  dimensions: string
  code: string
  image: string
  images?: string[]
  description: string
  descriptionAr: string
  longDescription: string
  longDescriptionAr: string
  features: string[]
  featuresAr: string[]
  applications: string[]
  applicationsAr: string[]
}

export const products: Product[] = [
  {
    id: "v-500",
    slug: "500l-vertical-air-tank",
    name: "Vertical Air Receiver 500L",
    nameAr: "خزان هواء رأسي 500 لتر",
    category: "vertical",
    orientation: "vertical",
    finish: "painted",
    capacity: "500 L",
    capacityL: 500,
    workingPressure: "11 Bar",
    testPressure: "48 Bar",
    motorHP: "5-7.5 HP",
    weight: "120 Kg",
    dimensions: "D600 × H1982mm",
    code: "SVP11500-V01",
    image: "/images/tanks/vertical-500-blue.png",
    images: [
      "/images/tanks/vertical-500-blue.png",
      "/images/tanks/vertical-500-red.png",
      "/images/tanks/vertical-500-galvanized.png",
    ],
    description: "Compact vertical receiver with a small footprint for industrial compressed-air systems.",
    descriptionAr: "خزان رأسي مدمج بمساحة تركيب صغيرة لأنظمة الهواء المضغوط الصناعية.",
    longDescription:
      "The 500L vertical receiver is a practical solution when floor space is limited. SEROP COMP manufactures vertical receivers in standard and custom finishes with tested welds and documented pressure testing.",
    longDescriptionAr:
      "الخزان الرأسي 500 لتر حل عملي عند محدودية مساحة التركيب. تصنع سيروب كومب الخزانات الرأسية بتشطيبات قياسية أو مخصصة مع لحامات مختبرة واختبارات ضغط موثقة.",
    features: [
      "Space-saving vertical layout",
      "Standard 11 bar working pressure",
      "Tested at 1.5x working pressure",
      "Multiple connection options",
      "5-year tank warranty",
    ],
    featuresAr: [
      "تصميم رأسي موفر للمساحة",
      "ضغط تشغيل قياسي 11 بار",
      "اختبار عند 1.5 من ضغط التشغيل",
      "خيارات متعددة للمخارج",
      "ضمان 5 سنوات على الخزان",
    ],
    applications: ["Manufacturing lines", "Automotive service", "Packaging", "Pneumatic tools"],
    applicationsAr: ["خطوط الإنتاج", "خدمة السيارات", "التعبئة والتغليف", "العدد الهوائية"],
  },
  {
    id: "v-900",
    slug: "900l-vertical-air-tank",
    name: "Vertical Air Receiver 900L",
    nameAr: "خزان هواء رأسي 900 لتر",
    category: "vertical",
    orientation: "vertical",
    finish: "painted",
    capacity: "900 L",
    capacityL: 900,
    workingPressure: "11 Bar",
    testPressure: "48 Bar",
    motorHP: "7.5-10 HP",
    weight: "190 Kg",
    dimensions: "D800 × H2214mm",
    code: "SVP11900-V01",
    image: "/images/tanks/vertical-900-blue.png",
    images: [
      "/images/tanks/vertical-900-blue.png",
      "/images/tanks/vertical-900-red.png",
      "/images/tanks/vertical-900-galvanized.png",
    ],
    description: "Vertical receiver with larger buffer volume for medium-duty compressed-air systems.",
    descriptionAr: "خزان رأسي بسعة أكبر لأنظمة الهواء المضغوط متوسطة الحمل.",
    longDescription:
      "The 900L vertical receiver bridges the gap between light and heavy industrial demand. Built from pressure-vessel steel with a certified painted finish, it provides stable air supply for mid-size compressor systems.",
    longDescriptionAr:
      "يمثل الخزان الرأسي 900 لتر الحل الوسط بين الاستخدامات الخفيفة والثقيلة. مصنوع من صلب أوعية الضغط بتشطيب دهان معتمد.",
    features: [
      "900L certified buffer volume",
      "Standard 11 bar working pressure",
      "Tested at 1.5x working pressure",
      "CE / ISO 16528 certified",
      "SEROP COMP identification plate",
    ],
    featuresAr: [
      "سعة احتياطية 900 لتر معتمدة",
      "ضغط تشغيل قياسي 11 بار",
      "اختبار عند 1.5 من ضغط التشغيل",
      "معتمد CE / ISO 16528",
      "لوحة تعريف سيروب كومب",
    ],
    applications: ["Industrial workshops", "Manufacturing lines", "Compressor packages", "Automotive plants"],
    applicationsAr: ["الورش الصناعية", "خطوط الإنتاج", "مجموعات الضواغط", "مصانع السيارات"],
  },
  {
    id: "v-1000",
    slug: "1000l-vertical-air-tank",
    name: "Vertical Air Receiver 1000L",
    nameAr: "خزان هواء رأسي 1000 لتر",
    category: "vertical",
    orientation: "vertical",
    finish: "painted",
    capacity: "1000 L",
    capacityL: 1000,
    workingPressure: "11 Bar",
    testPressure: "48 Bar",
    motorHP: "10-15 HP",
    weight: "240.66 Kg",
    dimensions: "D800 × H2413mm",
    code: "SVP1101K-V03",
    image: "/images/tanks/vertical-1000-blue.png",
    description: "Mid-capacity vertical receiver for continuous-duty compressed-air systems.",
    descriptionAr: "خزان رأسي متوسط السعة لأنظمة الهواء المضغوط ذات التشغيل المستمر.",
    longDescription:
      "The 1000L vertical receiver supports larger compressor systems while keeping a clean installation footprint. It can be supplied with painted, epoxy, or custom coating systems according to the operating environment.",
    longDescriptionAr:
      "الخزان الرأسي 1000 لتر يدعم أنظمة ضواغط أكبر مع الحفاظ على مساحة تركيب منظمة. يمكن توريده بدهان قياسي أو إيبوكسي أو تشطيب مخصص حسب بيئة التشغيل.",
    features: [
      "1000L certified capacity",
      "Painted or epoxy finish options",
      "Pressure-test documentation",
      "SEROP COMP identification plate",
      "Custom nozzles on request",
    ],
    featuresAr: [
      "سعة معتمدة 1000 لتر",
      "خيارات دهان أو إيبوكسي",
      "توثيق اختبار الضغط",
      "لوحة تعريف سيروب كومب",
      "مخارج مخصصة عند الطلب",
    ],
    applications: ["Factories", "Industrial workshops", "Food plants", "Production lines"],
    applicationsAr: ["المصانع", "الورش الصناعية", "مصانع الأغذية", "خطوط الإنتاج"],
  },
  {
    id: "v-2000",
    slug: "2000l-vertical-air-tank",
    name: "Vertical Air Receiver 2000L",
    nameAr: "خزان هواء رأسي 2000 لتر",
    category: "vertical",
    orientation: "vertical",
    finish: "painted",
    capacity: "2000 L",
    capacityL: 2000,
    workingPressure: "11 Bar",
    testPressure: "48 Bar",
    motorHP: "20-30 HP",
    weight: "436.5 Kg",
    dimensions: "D1000 × H2827mm",
    code: "SVP1102K-V02",
    image: "/images/tanks/vertical-2000-blue.png",
    description: "Large vertical receiver for high-flow industrial compressed-air demand.",
    descriptionAr: "خزان رأسي كبير لتطبيقات الهواء المضغوط ذات معدلات التدفق العالية.",
    longDescription:
      "The 2000L vertical receiver is suitable for large compressed-air networks and continuous industrial demand. The vessel can be built with inspection openings, custom ports, and protective coating systems.",
    longDescriptionAr:
      "الخزان الرأسي 2000 لتر مناسب لشبكات الهواء المضغوط الكبيرة والاحتياج الصناعي المستمر. يمكن تصنيع الوعاء بفتحات فحص ومخارج مخصصة وأنظمة حماية بالدهان.",
    features: [
      "Large vertical storage volume",
      "Inspection and drain options",
      "Painted finish with custom RAL colors",
      "Hydrostatic testing before delivery",
      "Export documentation available",
    ],
    featuresAr: [
      "حجم تخزين رأسي كبير",
      "خيارات فحص وتصريف",
      "دهان بألوان RAL مخصصة",
      "اختبار هيدروستاتيك قبل التسليم",
      "إمكانية تجهيز وثائق التصدير",
    ],
    applications: ["Heavy industry", "Large factories", "Process lines", "Export projects"],
    applicationsAr: ["الصناعات الثقيلة", "المصانع الكبيرة", "خطوط العمليات", "مشروعات التصدير"],
  },
  {
    id: "v-3000",
    slug: "3000l-vertical-air-tank",
    name: "Vertical Air Receiver 3000L",
    nameAr: "خزان هواء رأسي 3000 لتر",
    category: "vertical",
    orientation: "vertical",
    finish: "painted",
    capacity: "3000 L",
    capacityL: 3000,
    workingPressure: "11 Bar",
    testPressure: "48 Bar",
    motorHP: "30-40 HP",
    weight: "694.5 Kg",
    dimensions: "D1200 × H2770mm",
    code: "SVP1103K-V01",
    image: "/images/tanks/vertical-3000-blue.png",
    images: [
      "/images/tanks/vertical-3000-blue.png",
      "/images/tanks/vertical-3000-red.png",
      "/images/tanks/vertical-3000-galvanized.png",
    ],
    description: "Large vertical receiver for high-volume industrial compressed-air systems.",
    descriptionAr: "خزان رأسي كبير لأنظمة الهواء المضغوط الصناعية عالية الحجم.",
    longDescription:
      "The 3000L vertical receiver handles the highest sustained demand across large factories and industrial networks. Built from 8mm pressure-vessel steel with 1200mm diameter, it delivers reliable buffer volume for multi-compressor systems.",
    longDescriptionAr:
      "الخزان الرأسي 3000 لتر مصنوع من صلب أوعية الضغط بسماكة 8 مم وقطر 1200 مم، ويوفر سعة احتياطية عالية لأنظمة الضواغط المتعددة في المصانع الكبيرة.",
    features: [
      "3000L certified capacity",
      "D1200 × H2770mm — 8mm shell thickness",
      "11 Bar working pressure, tested at 16 Bar",
      "Safety valve, 3\" inlet/outlet connections",
      "Electrostatic painted finish",
    ],
    featuresAr: [
      "سعة معتمدة 3000 لتر",
      "D1200 × H2770mm — سماكة جدار 8 مم",
      "ضغط تشغيل 11 بار، اختبار عند 16 بار",
      "صمام أمان، مخارج دخول وخروج 3 بوصة",
      "دهان كهروستاتيكي",
    ],
    applications: ["Large factories", "Multi-compressor systems", "Heavy industry", "Export projects"],
    applicationsAr: ["المصانع الكبيرة", "أنظمة الضواغط المتعددة", "الصناعات الثقيلة", "مشروعات التصدير"],
  },
  // ── Horizontal tanks ──────────────────────────────────────────────────────
  {
    id: "h-50",
    slug: "50l-horizontal-air-tank",
    name: "Horizontal Air Receiver 50L",
    nameAr: "خزان هواء أفقي 50 لتر",
    category: "horizontal",
    orientation: "horizontal",
    finish: "painted",
    capacity: "50 L",
    capacityL: 50,
    workingPressure: "11 Bar",
    testPressure: "48 Bar",
    motorHP: "1–1.5 HP",
    weight: "18 Kg",
    dimensions: "L900 × D350mm",
    code: "SHP11050-H01",
    image: "/images/tanks/horizontal-50-blue.png",
    images: [
      "/images/tanks/horizontal-50-blue.png",
      "/images/tanks/horizontal-50-red.png",
      "/images/tanks/horizontal-50-galvanized.png",
    ],
    description: "Compact horizontal receiver for small compressor systems where vertical height is limited.",
    descriptionAr: "خزان أفقي مدمج لأنظمة الضواغط الصغيرة حيث الارتفاع محدود.",
    longDescription: "The 50L horizontal receiver is ideal for compact workshops and low-ceiling environments. Available in painted blue, painted red, and galvanized finishes.",
    longDescriptionAr: "الخزان الأفقي 50 لتر مثالي للورش المدمجة والبيئات ذات السقف المنخفض. متوفر بتشطيبات دهان أزرق وأحمر وجلفنة.",
    features: ["Horizontal compact layout", "3 finish options: blue, red, galvanized", "11 Bar working pressure", "Space-saving footprint", "5-year tank warranty"],
    featuresAr: ["تصميم أفقي مدمج", "3 تشطيبات: أزرق، أحمر، مجلفن", "ضغط تشغيل 11 بار", "مساحة تركيب صغيرة", "ضمان 5 سنوات"],
    applications: ["Small workshops", "Dental clinics", "Car service", "Pneumatic tools"],
    applicationsAr: ["الورش الصغيرة", "عيادات الأسنان", "خدمة السيارات", "العدد الهوائية"],
  },
  {
    id: "h-100",
    slug: "100l-horizontal-air-tank",
    name: "Horizontal Air Receiver 100L",
    nameAr: "خزان هواء أفقي 100 لتر",
    category: "horizontal",
    orientation: "horizontal",
    finish: "painted",
    capacity: "100 L",
    capacityL: 100,
    workingPressure: "11 Bar",
    testPressure: "48 Bar",
    motorHP: "1.5–2 HP",
    weight: "28 Kg",
    dimensions: "L1050 × D430mm",
    code: "SHP11100-H01",
    image: "/images/tanks/horizontal-100-blue.png",
    images: [
      "/images/tanks/horizontal-100-blue.png",
      "/images/tanks/horizontal-100-red.png",
    ],
    description: "Mid-small horizontal receiver for low-ceiling industrial and workshop environments.",
    descriptionAr: "خزان أفقي متوسط صغير للبيئات الصناعية والورش ذات الأسقف المنخفضة.",
    longDescription: "The 100L horizontal receiver provides a practical buffer for 1.5–2 HP compressor systems in space-constrained environments. Available in blue and red painted finishes.",
    longDescriptionAr: "يوفر الخزان الأفقي 100 لتر احتياطيًا عمليًا لأنظمة الضواغط في البيئات المحدودة المساحة. متوفر بتشطيبات دهان أزرق وأحمر.",
    features: ["100L horizontal buffer", "2 finish options: blue, red", "11 Bar working pressure", "Low-ceiling compatible", "CE / ISO 16528"],
    featuresAr: ["خزان احتياطي أفقي 100 لتر", "تشطيبان: أزرق وأحمر", "ضغط تشغيل 11 بار", "مناسب للأسقف المنخفضة", "معتمد CE / ISO 16528"],
    applications: ["Workshops", "Dental clinics", "Garages", "Light manufacturing"],
    applicationsAr: ["الورش", "عيادات الأسنان", "الجراجات", "التصنيع الخفيف"],
  },
  {
    id: "h-200",
    slug: "200l-horizontal-air-tank",
    name: "Horizontal Air Receiver 200L",
    nameAr: "خزان هواء أفقي 200 لتر",
    category: "horizontal",
    orientation: "horizontal",
    finish: "painted",
    capacity: "200 L",
    capacityL: 200,
    workingPressure: "11 Bar",
    testPressure: "48 Bar",
    motorHP: "2–3 HP",
    weight: "42 Kg",
    dimensions: "L1200 × D500mm",
    code: "SHP11200-H01",
    image: "/images/tanks/horizontal-200-blue.png",
    images: [
      "/images/tanks/horizontal-200-blue.png",
      "/images/tanks/horizontal-200-red.png",
      "/images/tanks/horizontal-200-galvanized.png",
    ],
    description: "Compact horizontal receiver for workshops with limited ceiling height.",
    descriptionAr: "خزان أفقي مدمج للورش ذات ارتفاع محدود.",
    longDescription: "The 200L horizontal receiver is the ideal mid-step between 100L and 300L systems. Available in blue, red, and galvanized finishes for standard and corrosive environments.",
    longDescriptionAr: "الخزان الأفقي 200 لتر هو الحل المثالي بين أنظمة 100 و300 لتر. متوفر بتشطيبات أزرق وأحمر ومجلفن للبيئات القياسية والمعرضة للتآكل.",
    features: ["200L horizontal buffer", "3 finish options: blue, red, galvanized", "11 Bar working pressure", "Low-ceiling compatible", "CE / ISO 16528"],
    featuresAr: ["خزان احتياطي أفقي 200 لتر", "3 تشطيبات: أزرق وأحمر ومجلفن", "ضغط تشغيل 11 بار", "مناسب للأسقف المنخفضة", "معتمد CE / ISO 16528"],
    applications: ["Workshops", "Dental clinics", "Garages", "Light manufacturing"],
    applicationsAr: ["الورش", "عيادات الأسنان", "الجراجات", "التصنيع الخفيف"],
  },
  {
    id: "h-300",
    slug: "300l-horizontal-air-tank",
    name: "Horizontal Air Receiver 300L",
    nameAr: "خزان هواء أفقي 300 لتر",
    category: "horizontal",
    orientation: "horizontal",
    finish: "painted",
    capacity: "300 L",
    capacityL: 300,
    workingPressure: "11 Bar",
    testPressure: "48 Bar",
    motorHP: "3–5 HP",
    weight: "65 Kg",
    dimensions: "L1350 × D560mm",
    code: "SHP11300-H01",
    image: "/images/tanks/horizontal-300-blue.png",
    images: [
      "/images/tanks/horizontal-300-blue.png",
      "/images/tanks/horizontal-300-galvanized.png",
    ],
    description: "Mid-capacity horizontal receiver available in painted and galvanized finishes.",
    descriptionAr: "خزان أفقي متوسط السعة متوفر بتشطيبات دهان ومجلفن.",
    longDescription: "The 300L horizontal receiver handles medium-duty compressed-air demand in low-ceiling factories. Available in standard painted blue and hot-dip galvanized finishes for corrosive environments.",
    longDescriptionAr: "يتعامل الخزان الأفقي 300 لتر مع متطلبات الهواء المضغوط متوسطة الحمل في المصانع ذات الأسقف المنخفضة. متوفر بدهان أزرق قياسي وجلفنة غمس لبيئات التآكل.",
    features: ["300L horizontal capacity", "Painted or galvanized finish", "11 Bar working pressure", "Corrosion-resistant option", "Documented pressure test"],
    featuresAr: ["سعة أفقية 300 لتر", "دهان أو جلفنة", "ضغط تشغيل 11 بار", "خيار مقاوم للصدأ", "اختبار ضغط موثق"],
    applications: ["Factories", "Workshops", "Automotive service", "Industrial lines"],
    applicationsAr: ["المصانع", "الورش", "خدمة السيارات", "الخطوط الصناعية"],
  },
  {
    id: "h-500",
    slug: "500l-horizontal-air-tank",
    name: "Horizontal Air Receiver 500L",
    nameAr: "خزان هواء أفقي 500 لتر",
    category: "horizontal",
    orientation: "horizontal",
    finish: "painted",
    capacity: "500 L",
    capacityL: 500,
    workingPressure: "11 Bar",
    testPressure: "48 Bar",
    motorHP: "5–7.5 HP",
    weight: "95 Kg",
    dimensions: "L1600 × D620mm",
    code: "SHP11500-H01",
    image: "/images/tanks/horizontal-500-blue.png",
    images: [
      "/images/tanks/horizontal-500-blue.png",
      "/images/tanks/horizontal-500-red.png",
      "/images/tanks/horizontal-500-galvanized.png",
    ],
    description: "Large horizontal receiver for industrial compressed-air systems with height restrictions.",
    descriptionAr: "خزان أفقي كبير لأنظمة الهواء المضغوط الصناعية ذات قيود الارتفاع.",
    longDescription: "The 500L horizontal receiver delivers the buffer volume of a full industrial system while fitting in low-ceiling environments. Three finish options: painted blue, painted red, and galvanized.",
    longDescriptionAr: "يوفر الخزان الأفقي 500 لتر سعة احتياطية لنظام صناعي كامل مع ملاءمة البيئات ذات الأسقف المنخفضة. ثلاثة تشطيبات: دهان أزرق وأحمر وجلفنة.",
    features: ["500L horizontal buffer", "3 finish options: blue, red, galvanized", "11 Bar working pressure", "CE / ISO 16528 certified", "5-year tank warranty"],
    featuresAr: ["خزان احتياطي أفقي 500 لتر", "3 تشطيبات: أزرق وأحمر ومجلفن", "ضغط تشغيل 11 بار", "معتمد CE / ISO 16528", "ضمان 5 سنوات على الخزان"],
    applications: ["Factories", "Industrial workshops", "Packaging lines", "Automotive plants"],
    applicationsAr: ["المصانع", "الورش الصناعية", "خطوط التعبئة", "مصانع السيارات"],
  },
  {
    id: "h-900",
    slug: "900l-horizontal-air-tank",
    name: "Horizontal Air Receiver 900L",
    nameAr: "خزان هواء أفقي 900 لتر",
    category: "horizontal",
    orientation: "horizontal",
    finish: "painted",
    capacity: "900 L",
    capacityL: 900,
    workingPressure: "11 Bar",
    testPressure: "48 Bar",
    motorHP: "7.5–10 HP",
    weight: "165 Kg",
    dimensions: "L1900 × D780mm",
    code: "SHP11900-H01",
    image: "/images/tanks/horizontal-900-blue.png",
    description: "High-capacity horizontal receiver for demanding industrial compressed-air systems.",
    descriptionAr: "خزان أفقي عالي السعة للأنظمة الصناعية الكثيفة للهواء المضغوط.",
    longDescription: "The 900L horizontal receiver is built for demanding production environments where vertical installation is not possible. Supplied in painted blue finish with full hydrostatic test documentation.",
    longDescriptionAr: "الخزان الأفقي 900 لتر مصنوع لبيئات الإنتاج المكثفة حيث لا يمكن التركيب الرأسي. يُورَّد بدهان أزرق مع وثائق اختبار هيدروستاتيكي كامل.",
    features: ["900L horizontal certified capacity", "Painted blue finish", "11 Bar working pressure", "CE / ISO 16528 certified", "Full hydrostatic test documentation"],
    featuresAr: ["سعة أفقية معتمدة 900 لتر", "دهان أزرق", "ضغط تشغيل 11 بار", "معتمد CE / ISO 16528", "وثائق اختبار هيدروستاتيكي كاملة"],
    applications: ["Large factories", "Compressor packages", "Manufacturing lines", "Heavy industry"],
    applicationsAr: ["المصانع الكبيرة", "مجموعات الضواغط", "خطوط الإنتاج", "الصناعات الثقيلة"],
  },
  {
    id: "h-1000",
    slug: "1000l-horizontal-air-tank",
    name: "Horizontal Air Receiver 1000L",
    nameAr: "خزان هواء أفقي 1000 لتر",
    category: "horizontal",
    orientation: "horizontal",
    finish: "galvanized",
    capacity: "1000 L",
    capacityL: 1000,
    workingPressure: "11 Bar",
    testPressure: "48 Bar",
    motorHP: "10–15 HP",
    weight: "195 Kg",
    dimensions: "L2100 × D780mm",
    code: "SHP1101K-H01",
    image: "/images/tanks/horizontal-1000-galvanized.png",
    description: "Extra-large galvanized horizontal receiver for corrosive or outdoor industrial environments.",
    descriptionAr: "خزان أفقي مجلفن كبير للبيئات الصناعية المعرضة للتآكل أو الخارجية.",
    longDescription: "The 1000L galvanized horizontal receiver provides maximum buffer capacity for heavy industrial systems while offering superior corrosion resistance for outdoor or humid environments.",
    longDescriptionAr: "يوفر الخزان الأفقي المجلفن 1000 لتر أقصى سعة احتياطية للأنظمة الصناعية الثقيلة مع مقاومة ممتازة للتآكل في البيئات الخارجية أو الرطبة.",
    features: ["1000L galvanized horizontal tank", "Superior corrosion resistance", "11 Bar working pressure", "Outdoor / humid environment rated", "CE / ISO 16528 certified"],
    featuresAr: ["خزان أفقي مجلفن 1000 لتر", "مقاومة فائقة للتآكل", "ضغط تشغيل 11 بار", "مناسب للبيئات الخارجية والرطبة", "معتمد CE / ISO 16528"],
    applications: ["Outdoor installations", "Coastal factories", "Humid environments", "Heavy industry"],
    applicationsAr: ["التركيبات الخارجية", "المصانع الساحلية", "البيئات الرطبة", "الصناعات الثقيلة"],
  },
]

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug)
}
